# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'MyBarnabot' do
	# For latest release in cocoapods
	pod 'JSQMessagesViewController'
end

target 'MyBarnabotTests' do

end

